### ISSUE TITLE
How to install it on ESPHome / Home Assistant

### ISSUE THREAD

**Issue by Anoxym** [JanM321/esphome-lg-controller#91]
Hi,

I try to install the code to my ESP32 via ESPHome on Home Assistant but there is error : Component not found: climate.
I put base.yaml in **/homeassistant/esphome/custom_components/lg_controller** with this : 

```
external_components:
  - source:
      type: local
      path: /config/esphome/custom_components/lg_controller
```

climate.py & lg-controller.h in **/homeassistant/esphome/custom_components/lg_controller** too.

template.yaml as a new device in ESHome Builder with :  `<<: !include ../esphome/custom_components/lg_controller/base.yaml` to include base.yaml

ERROR OUTPUT : 

```
INFO ESPHome 2024.12.2
INFO Reading configuration /config/esphome/hvac-controller.yaml...
ERROR Unable to load component climate:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 177, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/esphome/custom_components/lg_controller/climate.py", line 13, in <module>
    "LgController", cg.Component, uart.UARTDevice, climate.Climate
                                                   ^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'esphome.components.climate' has no attribute 'Climate' (most likely due to a circular import)
Failed config

climate: [source /config/esphome/../esphome/custom_components/lg_controller/base.yaml:55]
  
  Component not found: climate.
  - platform: lg_controller
    name: ''
    id: lgcontroller
    uart_id: ac_serial
    rx_pin: 
      number: GPIO36
      allow_other_uses: True
    fahrenheit: false
    is_slave_controller: false
    temperature_sensor: temp_sensor
    vane1: 
      name: Airflow 1 Up/Down
```

What is wrong ?

Thanks

**Comment by Anoxym** [comment]
Nobody have an idea?

**Comment by JanM321** [comment]
Is there a reason you can’t use the instructions in the README?

This describes an alternative option: https://github.com/JanM321/esphome-lg-controller/discussions/55

**Comment by Anoxym** [comment]
Sorry, the issue was actually that I hadn't created a components folder in ESPHome, and I had placed lg_controller in custom_components.

**Comment by Anoxym** [comment]
Sorry, the issue was actually that I hadn't created a components folder in ESPHome, and I had placed lg_controller in custom_components.
